### ISSUE TITLE
Player stats function and tests for Milestone 2

### ISSUE THREAD

**Issue by jnederlo** [UBC-MDS/rpuck#15]
This milestone requires that the player_stats function be competed and that there be at least 1 unit test covering at least 2 - 3 edge cases. The requirements are detailed as follows:

- [x] Iteratively code up the function.
- [x] At least 1 unit test.
- [x] The unit test should cover at least 2 - 3 edge cases.
- [x] The test(s) should cover all branches of program flow (i.e. both sides of an if-statement).
- [x] Update the documentation in response to the coding and the tests for any changes.
- [x] Document the test function(s).
- [x] Check the that the code passes the tests.
- [x] Write the test in the testthat folder.

I have thought about the possible tests, and some ideas are listed below:

- Check that no more and now fewer than 100 results are returned.
- Make sure the end_date is at least equal to or grater than the start_date.
- Ensure the start_date and end_date are of the appropriate type.
- Make sure the start_date and end_date are valid dates to query.
  - Update the documentation describing what the valid dates are.
- Make sure the default values for the current season are appropriate (i.e. if the arguments are left blank).
- Check that the function returns a data.frame object.
- Check that the API request returns a valid response. 
  - This could either be an assert, and/or a try/catch statement. 
- Implement a system to handle when bad responses are returned.
- Identify why a bad response was made.
  - Test that the URL is in-fact correctly specified.
