### ISSUE TITLE
draft_pick function for milestone 2

### ISSUE THREAD

**Issue by PolinaRomanchenko** [UBC-MDS/rpuck#17]
Following steps need to be executed before milestone 2 deadline:

- [x]  Write the function body
- [x]  Document changes in docsting (if needed)
- [x]  User input error handling
- [x]  Tests for the output
- [x]  Docstrings for test functions
- [x]  Unit tests and
- [x]  Ideas for tests are, but not limited, to following:

User input tests and error handling (check inputted parameters)
Output testing (check if function returns pd.DataFrame)
Check output length if only default parameters are chosen
Check output length if only year/round_number were chosen
Check if output dataframe is not empty
