### ISSUE TITLE
Milestone 3 Deliverables  

### ISSUE THREAD

**Issue by PolinaRomanchenko** [UBC-MDS/rpuck#29]
**Continuous Integration (CI)**

- [x] Set up GitHub Actions for Continuous Integration (CI) and Continuous Deployment (CD).

**Integration tests**

- [x]  Add adequate integration tests.
- [x] Ensure the build status and GitHub Action logs show passing.

**Additional tests**
- [x] Add additional test cases.
- [x] Ensure minimum 90% branch coverage.
- [x]  The codecov.io button on the repo must communicate the coverage.

**Documentation**
- [x] use vignette package-wide documentation in R, as well as the pkgdown R package to set up a website for your package.
- [x] check if all docstrings are in place
- [x] include usage (this means a runnable example) and installation instructions in README.md files

**Final Check**
- [x] Before submission, all GitHub Actions workflows should run without error and be advertised as such using badges in the README.

**Comment by jnederlo** [comment]
Closed with PR #47 .
